version: '3.8'

services:
  keycloak-postgres:
    container_name: keycloak_postgres
    image: postgres:12.5-alpine
    command: -p ${DB_KEYCLOAK_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_KEYCLOAK_PASSWORD}
      POSTGRES_USER: ${DB_KEYCLOAK_USERNAME}
      POSTGRES_DB: ${DB_KEYCLOAK_DATABASE}
    env_file:
      - .env
    ports:
      - ${DB_KEYCLOAK_PORT}:${DB_KEYCLOAK_PORT}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_KEYCLOAK_USERNAME}", "-p", "${DB_KEYCLOAK_PORT}"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
    stdin_open: true
    tty: true
    volumes:
      - .docker/keycloak-postgres:/var/lib/postgresql/data

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:12.0.4
    command: -Dkeycloak.profile.feature.scripts=enabled -Dkeycloak.profile.feature.upload_scripts=enabled
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USERNAME}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_IMPORT: /tmp/realm-myrealm.json
      DB_VENDOR: postgres
      DB_ADDR: keycloak-postgres
      DB_PORT: ${DB_KEYCLOAK_PORT}
      DB_USER: ${DB_KEYCLOAK_USERNAME}
      DB_PASSWORD: ${DB_KEYCLOAK_PASSWORD}
      DB_DATABASE: ${DB_KEYCLOAK_DATABASE}
      DB_SCHEMA: public
    env_file:
      - .env
    ports:
      - ${KEYCLOAK_PORT}:${KEYCLOAK_PORT}
    depends_on:
      keycloak-postgres:
        condition: service_healthy
    volumes:
      - .docker/keycloak:/tmp